package edu.nju.comparePrice.models;

// Generated 2014-3-26 7:32:39 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Brand generated by hbm2java
 */
@Entity
@Table(name = "brand", catalog = "comparepricedb")
public class Brand implements java.io.Serializable {

	private Integer id;
	private String name;
	private Boolean flag;
	private Integer weight;
	private Set commodities = new HashSet(0);
	private Set candidateWords = new HashSet(0);
	private Set specialWords = new HashSet(0);

	public Brand() {
	}

	public Brand(String name, Boolean flag, Integer weight, Set commodities,
			Set candidateWords, Set specialWords) {
		this.name = name;
		this.flag = flag;
		this.weight = weight;
		this.commodities = commodities;
		this.candidateWords = candidateWords;
		this.specialWords = specialWords;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 16)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "flag")
	public Boolean getFlag() {
		return this.flag;
	}

	public void setFlag(Boolean flag) {
		this.flag = flag;
	}

	@Column(name = "weight")
	public Integer getWeight() {
		return this.weight;
	}

	public void setWeight(Integer weight) {
		this.weight = weight;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "brand")
	public Set getCommodities() {
		return this.commodities;
	}

	public void setCommodities(Set commodities) {
		this.commodities = commodities;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "brand")
	public Set getCandidateWords() {
		return this.candidateWords;
	}

	public void setCandidateWords(Set candidateWords) {
		this.candidateWords = candidateWords;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "brand")
	public Set getSpecialWords() {
		return this.specialWords;
	}

	public void setSpecialWords(Set specialWords) {
		this.specialWords = specialWords;
	}

}
