package edu.nju.comparePrice.models;

// Generated 2014-3-19 22:36:57 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CandidateWord generated by hbm2java
 */
@Entity
@Table(name = "candidate_word", catalog = "comparepricedb")
public class CandidateWord implements java.io.Serializable {

	private int id;
	private String name;

	public CandidateWord() {
	}

	public CandidateWord(int id) {
		this.id = id;
	}

	public CandidateWord(int id, String name) {
		this.id = id;
		this.name = name;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", length = 16)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
