package edu.nju.comparePrice.models;

// Generated 2014-3-26 7:32:39 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Comment generated by hbm2java
 */
@Entity
@Table(name = "comment", catalog = "comparepricedb")
public class Comment implements java.io.Serializable {

	private Integer id;
	private Commodity commodity;
	private User user;
	private String details;
	private Boolean state;

	private Boolean specialstate;
	private Integer uid;
	private Integer cid;

	public Comment() {
	}

	public Comment(Commodity commodity, User user) {
		this.commodity = commodity;
		this.user = user;
	}

	public Comment(Commodity commodity, User user, String details,
			Boolean state, Boolean iscandidateword, Boolean specialstate) {
		this.commodity = commodity;
		this.user = user;
		this.details = details;
		this.state = state;
	
		this.specialstate = specialstate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cid", nullable = false)
	public Commodity getCommodity() {
		return this.commodity;
	}

	public void setCommodity(Commodity commodity) {
		this.commodity = commodity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "uid", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "details")
	public String getDetails() {
		return this.details;
	}

	public void setDetails(String details) {
		this.details = details;
	}

	@Column(name = "state")
	public Boolean getState() {
		return this.state;
	}

	public void setState(Boolean state) {
		this.state = state;
	}

	

	@Column(name = "specialstate")
	public Boolean getSpecialstate() {
		return this.specialstate;
	}

	public void setSpecialstate(Boolean specialstate) {
		this.specialstate = specialstate;
	}

	public Integer getUid() {
		return uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public Integer getCid() {
		return cid;
	}

	public void setCid(Integer cid) {
		this.cid = cid;
	}

}
