package edu.nju.comparePrice.models;

// Generated 2014-3-26 7:32:39 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Commodity generated by hbm2java
 */
@Entity
@Table(name = "commodity", catalog = "comparepricedb")
public class Commodity implements java.io.Serializable {

	private Integer id;
	private Brand brand;
	private Integer bid;
	private String name;
	private Double price;
	private Integer unit;
	private String link;
	private String onlineId;
	private Set forbidCommodities = new HashSet(0);
	private Set comments = new HashSet(0);

	public Commodity() {
	}

	public Commodity(Brand brand) {
		this.brand = brand;
	}

	public Commodity(Brand brand, String name, Double price, Integer unit,
			String link, String onlineId, Set forbidCommodities, Set comments) {
		this.brand = brand;
		this.name = name;
		this.price = price;
		this.unit = unit;
		this.link = link;
		this.onlineId = onlineId;
		this.forbidCommodities = forbidCommodities;
		this.comments = comments;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "brandId", nullable = false)
	public Brand getBrand() {
		return this.brand;
	}

	public void setBrand(Brand brand) {
		this.brand = brand;
	}

	@Column(name = "name", length = 16)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "price", precision = 22, scale = 0)
	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	@Column(name = "unit")
	public Integer getUnit() {
		return this.unit;
	}

	public void setUnit(Integer unit) {
		this.unit = unit;
	}

	@Column(name = "link")
	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

	@Column(name = "onlineId", length = 32)
	public String getOnlineId() {
		return this.onlineId;
	}

	public void setOnlineId(String onlineId) {
		this.onlineId = onlineId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "commodity")
	public Set getForbidCommodities() {
		return this.forbidCommodities;
	}

	public void setForbidCommodities(Set forbidCommodities) {
		this.forbidCommodities = forbidCommodities;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "commodity")
	public Set getComments() {
		return this.comments;
	}

	public void setComments(Set comments) {
		this.comments = comments;
	}

	public Integer getBid() {
		return bid;
	}

	public void setBid(Integer bid) {
		this.bid = bid;
	}

}
