package edu.nju.comparePrice.models;

// Generated 2014-3-19 22:36:57 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ForbidCommodity generated by hbm2java
 */
@Entity
@Table(name = "forbid_commodity", catalog = "comparepricedb")
public class ForbidCommodity implements java.io.Serializable {

	private int id;
	private Commodity commodity;

	public ForbidCommodity() {
	}

	public ForbidCommodity(int id, Commodity commodity) {
		this.id = id;
		this.commodity = commodity;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cid", nullable = false)
	public Commodity getCommodity() {
		return this.commodity;
	}

	public void setCommodity(Commodity commodity) {
		this.commodity = commodity;
	}

}
