package edu.nju.comparePrice.models;

// Generated 2014-3-26 7:32:39 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ForbidCommodity generated by hbm2java
 */
@Entity
@Table(name = "forbid_commodity", catalog = "comparepricedb", uniqueConstraints = @UniqueConstraint(columnNames = "cid"))
public class ForbidCommodity implements java.io.Serializable {

	private Integer id;
	private Commodity commodity;
	private Integer cid;
	private String name;

	public ForbidCommodity() {
	}

	public ForbidCommodity(Commodity commodity) {
		this.commodity = commodity;
	}

	public ForbidCommodity(Commodity commodity, String name) {
		this.commodity = commodity;
		this.name = name;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cid", unique = true, nullable = false)
	public Commodity getCommodity() {
		return this.commodity;
	}

	public void setCommodity(Commodity commodity) {
		this.commodity = commodity;
	}

	@Column(name = "name", length = 16)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getCid() {
		return cid;
	}

	public void setCid(Integer cid) {
		this.cid = cid;
	}

}
